<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://KonferencijeWS.etfbl.net" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://KonferencijeWS.etfbl.net" xmlns:intf="http://KonferencijeWS.etfbl.net" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://KonferencijeWS.etfbl.net" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="konferencijeZaTekuciMjesec">
    <complexType/>
   </element>
   <element name="konferencijeZaTekuciMjesecResponse">
    <complexType>
     <sequence>
      <element name="konferencijeZaTekuciMjesecReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="konferencijeZaTekuciMjesecRequest">

      <wsdl:part element="impl:konferencijeZaTekuciMjesec" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="konferencijeZaTekuciMjesecResponse">

      <wsdl:part element="impl:konferencijeZaTekuciMjesecResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="KonferencijeWS">

      <wsdl:operation name="konferencijeZaTekuciMjesec">

         <wsdl:input message="impl:konferencijeZaTekuciMjesecRequest" name="konferencijeZaTekuciMjesecRequest">

       </wsdl:input>

         <wsdl:output message="impl:konferencijeZaTekuciMjesecResponse" name="konferencijeZaTekuciMjesecResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="KonferencijeWSSoapBinding" type="impl:KonferencijeWS">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="konferencijeZaTekuciMjesec">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="konferencijeZaTekuciMjesecRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="konferencijeZaTekuciMjesecResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="KonferencijeWSService">

      <wsdl:port binding="impl:KonferencijeWSSoapBinding" name="KonferencijeWS">

         <wsdlsoap:address location="http://localhost:8085/CyberConferenceKonfWS/services/KonferencijeWS"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
